spring:
  config:
    import: optional:file:./env.properties
  application:
    name: springboot-java-rest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_java_rest?useTimezone=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    root: info
    #marcosmello04.github: debug
    #spring.jpa.open-in-view
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true